### ISSUE TITLE
The license in use seems problematic for some groups of developers

### ISSUE THREAD

**Issue by bbottema** [markenwerk/java-utils-mail-dkim#10]
Hi @toKrause, 

Is there a specific reason for using the (L)GPL licence and are you open to changing it perhaps? Here's a problem we are running into with this:

> GPL is difficult with Android development - the license requirement that any user can swap LGPL'd dependencies out is (apparently) incompatible with android app bundling. I'm no lawyer, but lawyers I've spoken to seem to think so. For what it's worth, the various fora on the internet do too. Here, for example, is a blog post explaining the issue (as far as I understand it)
> https://xebia.com/blog/the-lgpl-on-android/ .

Because of this, I noticed users forking Simple Java Mail only to remove all code regarding the DKIM library to avoid [Copyleft](https://en.wikipedia.org/wiki/Copyleft) issues.

Also, here's a [SO answer](https://softwareengineering.stackexchange.com/a/326325/176541) giving some insight into the reasoning behind LGPL and Oracle's variation "GPL with classpath exception". One thing that immediately stands out is that (L)GPL was originally written for C/C++ applications.

If you compare [LGPL](https://tldrlegal.com/license/gnu-lesser-general-public-license-v3-(lgpl-3)) with [Apache v2](https://tldrlegal.com/license/apache-license-2.0-(apache-2.0)), there is a lot of overlap (Apache V2 on the left):
![image](https://user-images.githubusercontent.com/2115718/44456488-f7a81a00-a600-11e8-9f82-c1ac26f37ed2.png)

The repo you forked from also used Apache v2, so I guess you had a specific reason for switching the L(GPL). Any thoughts on all this are very welcome.

**Comment by bbottema** [comment]
Hi @toKrause, have you had some time to think about this?

**Comment by toKrause** [comment]
Hi, I'm not a lawyer and I really don't enjoy having to deal with license stuff. In the hope of making things easier for me and having less trouble in the future, I've changed the license to LGPL, so that this library and my S/MIME library would have the same license. Apparently I've made the wring call. I'm not sure if i can repair the "damage", but I'm going to look into.

**Comment by bbottema** [comment]
@toKrause, any update here? If you want I can provide a pull-request that switches the license file (with Apache v2). I think that is all that is needed if I'm not mistaken.

**Comment by bbottema** [comment]
@toKrause? Sorry for pestering you, but this should be a quick fix. Is there anything specific holding you back? Can I help?

**Comment by toKrause** [comment]
Nothing specific. I just have a lot going on in my life, so I have little time left to manage this project. I just released a new version under the original license.

**Comment by bbottema** [comment]
Understandable and thank you so much for changing the licence!

**Comment by toKrause** [comment]
Thanks for your patience. The new version number will be 1.1.12. It usually takes a few hours for new releases to be visible in Maven Central.
