### ISSUE TITLE
Possible to combine DKIM and SMIME?

### ISSUE THREAD

**Issue by bbottema** [markenwerk/java-utils-mail-dkim#13]
Hi,

You provide libraries for both DKIM and S/MIME signing (and encryption). Can these be combined? They work by returning a new MimeMessage / DkimMessage, so I'm not sure how to apply both.

**Comment by toKrause** [comment]
Hi. It is possible. I can provide a simple example tomorrow.

**Comment by bbottema** [comment]
Thanks @toKrause, is it something like this?

```java
MimeMessage message = ...;

message = SmimeUtil.sign(session, message, smimeKey);
message = SmimeUtil.encrypt(session, message, certificate);
message = new DkimMessage(message, dkimSigner);
```
I suspect it's important to do DKIM last.

/edit: yeah I think I got this working. Can you confirm this is the way to go?

**Comment by toKrause** [comment]
HI, your example code looks right.

Adding the DKIM signature as the last step is certainly correct.

Personally, I'd like to perform the S/MIME operations in the opposite order. Encrypting before signing enables the receiver to verify the received messages authenticity first. It is then possible to reject a potentially unauthentic message without even decrypting it (and it's possible harmful content). But I suspect that makes very little difference with real world mail clients.

I've never head any issues with the order S/MIME encrypt, S/MIME sign, DKIM sign.
