### ISSUE TITLE
Case Sensitive header names dkim Sign

### ISSUE THREAD

**Issue by bhanu7pk** [markenwerk/java-utils-mail-dkim#18]
There is no way we can provide case insensitive header list to sign the message using this dkim library. Particularly From, To, Subject headers. 

I tried adding 'from', 'FROM' header names using addHeaderToSign method, but it throws exception if mail does not contain 'From' header in camel case. 

According to SMTP/MIME RFC, email header names are case insensitive. But, inside this library headersToSign variable is hard-coded with predefined list. 

The comparison for header names while signing the message should be case-insensitive. At present it is case sensitive.

**Comment by toKrause** [comment]
I'll look into it. This shouldn't be too hard to fix.

**Comment by bhanu7pk** [comment]
> I'll look into it. This shouldn't be too hard to fix.

Thanks for the response. Waiting for the fix .

**Comment by shahnarendra4u** [comment]
> I'll look into it. This shouldn't be too hard to fix.

Added 2 possible fixes, kindly review either of it and merge, if it looks ok. 

https://github.com/markenwerk/java-utils-mail-dkim/pull/20
https://github.com/markenwerk/java-utils-mail-dkim/pull/21

**Comment by toKrause** [comment]
Hi, I finally have some time to spent on this. A new version should be available shortly.
