### ISSUE TITLE
DkimSigner.checkIdentity for email with Display Name doesn't work

### ISSUE THREAD

**Issue by sbtnk** [markenwerk/java-utils-mail-dkim#22]
Hello,
I use as From address email with some descriptive name like
`"Some descriptive name" <email@somedomain.com>`
and in such case DkimSigner.checkIdentity doesn't resolve it as valid identity.
It returns exception
`The domain part of "Some descriptive name" <email@somedomain.com> isn't somedomain.com or a subdomain thereof`

**Comment by toKrause** [comment]
Hi, 

the identity property will be used by the DKIM library as the `i`-tag in the generated DKIM headers. This tag is described in [section 3.5](https://tools.ietf.org/html/rfc6376#section-3.5) of the DKIM specification. To quote the specification:

> The syntax is a standard email address where the local-part MAY be omitted.

That, as I read it, means that DKIM expects something like `email@somedomain.com` or `@somedomain.com` as valid values for this tag. I'm not sure that a DKIM verifier would be happy with something like `"Some descriptive name" <email@somedomain.com>`.

That being said, it shouldn't be too complicated to detect a descriptive email address, throw away the descriptive part and use only the actual email address; i.e. use only `email@somedomain.com` in the given example.

I'll look into it.

**Comment by toKrause** [comment]
Hi, 

I've reread the specification and to quite it again:

> The AUID is specified as having the same syntax as an email address but it need not have the same semantics.

The AUID is the value of the `i`-tag in the generated DKIM header, i.e. the value of the `identity`-parameter in the DKIM library. While it would be possible to extract a syntactically valid value from a input string that represents a descriptive email, I don't think it is a good idea to let the DKIM library guess the intention of the signer.

Therefor, if a signer wishes to populate the `i`-tag, they should pass the intended value as the `identity`-parameter. The DKIM library should only check if the passed value is indeed valid in the given context (i.e., check, that it corresponds to the given `domain`-parameter / 'd'-tag).

I will close this issue for now. Feel free to reopen if if you think that this feature is necessary and appropriate for the DKIM library and you have an idea on how to keep the guesswork out of the DKIM library.

**Comment by sbtnk** [comment]
You're right. We need to extract simple form of email and put it into _identity_
