### ISSUE TITLE
Signature addition fails on "Subject" or "To" header missing 

### ISSUE THREAD

**Issue by shahnarendra4u** [markenwerk/java-utils-mail-dkim#23]
Actual: 
In email subject and to are optional field, and some of the auto-generated emails or emails containing cc or bcc might not have to field. Here library throws an exception with missing header and we have to ignore adding dkim signature on such emails. 

Expected: 
DKIM Signature should work without enforcement on optional fields

**Comment by toKrause** [comment]
I'll look into it.

**Comment by toKrause** [comment]
Sorry for the long delay. I removed the `Subject` and `To` headers from the set of mandatory headers. Version 1.4.0 should be available shortly.
