### ISSUE TITLE
Dkim validation fails if user sends an email with empty subject header

### ISSUE THREAD

**Issue by aluchava** [markenwerk/java-utils-mail-dkim#25]
Subject:
dkim=fail (signature did not verify)

**Comment by toKrause** [comment]
Hi,

sorry for the delayed reaction. I don't really have much time to maintain this library. 

Is this still an issue? I've tried sending a signed message with an empty subject line and have no problems. Both the [Thunderbird plugin](https://addons.thunderbird.net/de/thunderbird/addon/dkim-verifier/) and [dkimvalidator.com](https://dkimvalidator.com/) accept the generated signature as valid. 

This may be an issue withe the used DKIM verifyer.
