### ISSUE TITLE
DKIM KeyPair

### ISSUE THREAD

**Issue by MarcusBiel** [markenwerk/java-utils-mail-dkim#28]
Hi, I just need the DKIM KeyPair - how can I retrieve this with the library?
I see: DomainKey domainKey = DomainKeyUtil.getDomainKey("mydomain.com", "myselector");
But DomainKey doesn't seem to have a way to retrieve the private key or even the public key, as a simple String.

**Comment by toKrause** [comment]
Hi, 

domain keys only contain the public key of an RSA key pair. Domain keys are, after all, stored publicly readable in the DNS and DKIM versifiers only need the public key to do their job. It is therefore impossible to retrieve the private key of an RSA key pair from a domain key. 

RSA public keys are binary data, not character data. Therefore, RSA public keys have no natural string representation. They are, however, typically stored as a PEM file. PEM files look like this:

```
-----BEGIN PUBLIC KEY-----
MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQCf4lvVllV2eoDqxartI0bUiJXD
v+TVhFoGcheKocQyLGrTi8BKamhoDt8yKiecpCm1rZ/nRyxSqIAJFMV3y/XslSVV
2Sc48efPtrdViGUcGYNCC/KrqYNgCF7vRO2oAQ7ePPBohwcR1hzavGeY/AVxpEeI
vixQNmunxkdaqHCLuQIDAQAB
-----END PUBLIC KEY-----
 ```

PEM files consist of a begin-marker, the Base64-encoded binary public key (following the X.509 specification) and an end marker.

Domain keys contain the same Base64-encoded binary public key along with other data and look like this:

```
v=DKIM1;g=*;k=rsa;p=MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQCf4lvV
llV2eoDqxartI0bUiJXDv+TVhFoGcheKocQyLGrTi8BKamhoDt8yKiecpCm1rZ/n
RyxSqIAJFMV3y/XslSVV2Sc48efPtrdViGUcGYNCC/KrqYNgCF7vRO2oAQ7ePPBo
hwcR1hzavGeY/AVxpEeIvixQNmunxkdaqHCLuQIDAQAB;s=email;t=s
```

If your goal is to create a PEM file, you can retrieve the Base64-encoded binary public key using `DomainKeyUtil.getDomainKey("mydomain.com", "myselector").getTags().get('p')` and easily split int into multiple lines, prepend the begin-marker, append the end-marker and store the result. There is indeed no convenience method for this in the library.

But, as mentioned above, this will only get you the public key.

Hope this helps.
